"type:adr":
  - "adr/[0-9]*.md"

"type:docs":
  - "docs/**"
  - "rfc/**"

"type:config":
  - ".github/**"

"area:rules":
  - "adr/000[0-9]*.md"
  - "adr/00[1-9][0-9]*.md"
  - "docs/regras-gerais.md"

"area:tournament":
  - "adr/01[0-9][0-9]*.md"
  - "docs/formatos-de-jogo.md"

"area:ranking":
  - "adr/02[0-9][0-9]*.md"

"area:equipment":
  - "adr/03[0-9][0-9]*.md"

"area:conduct":
  - "adr/04[0-9][0-9]*.md"
